const constants = {
    DEFAULT_GAME_FIELD_SIZE: 4,
    DEFAULT_GAME_ITEM_SIZE: 100,
    GAME_ITEM_MOVE_DURATION: 400,
    GAME_FIELD_REFRESH_DURATION: 420,
    MINIMAL_MOUSE_SHIFT: 50
};

export default constants;